language: php
sudo: false

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - master

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls --verbose
